### ISSUE TITLE
Establish a test matrix

### ISSUE THREAD

**Issue by tonyfast** [omnisci/jupyterlab-omnisci#11]
The text matrix will explore different backends, renderers, and schemas.

* Backends: dataframe, ibis, ibis.mapd
* Renderers: json, png, mapd
* Schema: vega, vega-lite

**Comment by saulshanabrook** [comment]
https://robotframework.org/

https://github.com/robots-from-jupyter/robotkernel

https://www.cypress.io/

**Comment by tonyfast** [comment]
Hot off the presses

https://github.com/gtri/irobotframework

**Comment by saulshanabrook** [comment]
We have done this now in vega-ibis-transform
