### ISSUE TITLE
Data Cataloging

### ISSUE THREAD

**Issue by dharhas** [omnisci/jupyterlab-omnisci#78]
The goal is to enable use of OmniSci as an end to end workflow engine/pipeline.
Use Intake to build a data catalog of OmniSci databases
Intake to provide larger data sources that are outside omnisci (i.e on S3, Landsat etc.
Intake plugin for OmniSci internal data format and data catalogs
Develop federated catalogs based on intake/yaml data sources

**Comment by saulshanabrook** [comment]
Closing this for now.
