### ISSUE TITLE
UDF Enhancements

### ISSUE THREAD

**Issue by dharhas** [omnisci/jupyterlab-omnisci#79]
UDF Enhancements
UDF Documentation: Help to identify the proper personas and their use cases
UDF Documentation: Create additional documentation and examples for UDFs to better cater to use cases identified
Currently, all users can define UDFs which are global. This means that any user can delete or redefine UDFs defined by others. Implement session dependent UDF registration or alternate mechanism to mitigate this issue.
Currently, UDFs support only scalar arguments, that is, UDFs are applied by row. Implement support for UDF array arguments, this task is dependant on availability of OmniSci staff to implement prerequisite functionality

**Comment by saulshanabrook** [comment]
These are now tracked separately
