### ISSUE TITLE
[BUG] Installation on GCP results in non-functional notebook

### ISSUE THREAD

**Issue by marvin-hansen** [omnisci/jupyterlab-omnisci#95]
**Describe the bug**

Installation on GCP solution instance results in non-fuctional notebook without DB connection. 

**Affected version** 

DB: Enterprise Edition, Core v5.2.2, Backend Rendering Enabled (GPU) 

jupyterlab-omnisci: v0.10.1 

jupyterlab: 1.2.15

**Reproduce**

1) sudo yum update
The shipped DB release is ages old and needs a manual update to the current version

2) conda install -c conda-forge pymapd nodejs jaeger

3) pip install jupyterlab-omnisci "tornado<6" "notebook<6" 
 
4)  pip install jupyterlab==1.2.15
A newer version of jupyterlab does not work yet. Please add to the documentation  

5) jupyter labextension install   @jupyter-widgets/jupyterlab-manager  ibis-vega-transform   jupyterlab-server-proxy-saulshanabrook     jupyterlab-omnisci
 
 From:
 https://github.com/omnisci/jupyterlab-omnisci 
 
 
## Start JupyterLab:

jupyter lab --ip=0.0.0.0 --port=8888 

Firewall rule for port 8888 must be in place. Please add to the docks.

**Expected behavior**

Connect to the DB, on the same host, and query the DB.

**Actual behavior**

SQL console yields just a white space with no signs of activity.

IBIS connection throws the following error: 

> AttributeError: module 'ibis' has no attribute 'mapd'

**Extra Information**
> jupyter labextension list

JupyterLab v1.2.15
Known labextensions:
   app dir: /home/marvin_hansen/.conda/envs/default/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        ibis-vega-transform v4.0.0  enabled  OK
        jupyterlab-omnisci v1.0.1  enabled  OK
        jupyterlab-server-proxy-saulshanabrook v2.0.0  enabled  OK

**Comment by FDenker** [comment]
Hi were you able to resolve this issue / did you find any workaround for it?

**Comment by marvin-hansen** [comment]
Never solved.

I ditched omnisci already while ago.

Would go with Nebula Graph DB in my next project.
